import networkx as nx
import os

# CONFIGURATION
INPUT_FILE = "/home/yugp/projects/EricaAITutor/backend/scripts/erica_graph_storage/graph_chunk_entity_relation.graphml" # Path to your GraphRAG output
OUTPUT_FILE = "graph_yed_ready.graphml"

def make_graph_yed_ready(input_path, output_path):
    print(f"📂 Loading {input_path}...")
    
    try:
        # Load the graph
        G = nx.read_graphml(input_path)
    except Exception as e:
        print(f"❌ Error loading file: {e}")
        print("Make sure you are pointing to the correct .graphml file generated by your RAG pipeline.")
        return

    print(f"   - Nodes: {G.number_of_nodes()}")
    print(f"   - Edges: {G.number_of_edges()}")

    # --- FIX 1: VISIBLE LABELS ---
    # yEd looks for a 'label' attribute by default. 
    # GraphRAG usually stores the name in 'name' or 'entity_name'.
    count = 0
    for node, data in G.nodes(data=True):
        # Check commonly used keys for the node name
        possible_keys = ['name', 'entity_name', 'title', 'id']
        label_text = "Unknown"
        
        # Try to find a valid name
        for key in possible_keys:
            if key in data and data[key]:
                label_text = data[key]
                break
        
        # If we couldn't find a name attribute, use the node ID itself
        if label_text == "Unknown":
            label_text = node
            
        # Assign to 'label' which yEd auto-detects
        data['label'] = str(label_text)
        count += 1

    print(f"✅ fixed {count} labels for yEd visibility.")

    # --- FIX 2: PREVENT ERROR ON IMPORT ---
    # Sometimes complex data types in GraphRAG break yEd import. 
    # We convert all attributes to strings to be safe.
    for node, data in G.nodes(data=True):
        for k, v in data.items():
            data[k] = str(v)
            
    for u, v, data in G.edges(data=True):
        for k, v in data.items():
            data[k] = str(v)

    # Save
    print(f"💾 Saving to {output_path}...")
    nx.write_graphml(G, output_path)
    print("🚀 Done! You can now open this file in yEd.")

if __name__ == "__main__":
    # Check if input exists
    if os.path.exists(INPUT_FILE):
        make_graph_yed_ready(INPUT_FILE, OUTPUT_FILE)
    else:
        # Fallback: Create a dummy graph to demonstrate if file not found
        print(f"⚠️  Input file {INPUT_FILE} not found. Creating a dummy graph for demonstration...")
        G = nx.erdos_renyi_graph(10, 0.3)
        # Add some fake GraphRAG-style attributes
        idx = 0
        for n in G.nodes():
            G.nodes[n]["name"] = f"CONCEPT_{idx}"
            G.nodes[n]["description"] = "A generated concept for testing."
            idx += 1
        nx.write_graphml(G, "dummy_input.graphml")
        make_graph_yed_ready("dummy_input.graphml", OUTPUT_FILE)